server {
    listen 80;
    server_name www.regsure.app;
    return 301 https://regsure.app$request_uri;
}
server {
    listen 80;
    server_name regsure.app;
    location / { proxy_pass http://127.0.0.1:3000; include proxy_params; }
}
server {
    listen 80;
    server_name api.regsure.app;
    location / { proxy_pass http://127.0.0.1:3000; include proxy_params; }
}
server {
    listen 80;
    server_name eve.regsure.app;
    location / { proxy_pass http://127.0.0.1:2000; include proxy_params; }
}
